format = """
[â•­](fg:current_line)\
[â”€](fg:current_line)[î‚¶](fg:yellow)[ï€‡ ](fg:primary bg:yellow)\
$sudo\
$username\
$directory\
$git_branch\
$git_status\
$git_metrics\
$nix_shell\
$fill\
$nodejs\
$bun\
$deno\
$golang\
$kotlin\
$c\
$java\
$python\
$docker_context\
$rust\
$php\
$dart\
$haskell\
$aws\
$cmd_duration\
$time\
$line_break\
$character\
"""

palette = 'dracula'
add_newline = true

[palettes.dracula]
foreground = '#F8F8F2'
background = '#282A36'
current_line = '#44475A'
primary = '#1E1F29'
box = '#44475A'
blue = '#6272A4'
cyan = '#8BE9FD'
green = '#50FA7B'
orange = '#FFB86C'
pink = '#FF79C6'
purple = '#BD93F9'
red = '#FF5555'
yellow = '#F1FA8C'

[os]
format = '[â”€](fg:current_line)[î‚¶](fg:red)[$symbol ](fg:primary bg:red)[î‚´](fg:red)'
disabled = false

[os.symbols]
Alpine = 'ïŒ€'
Amazon = 'ï‰°'
Android = 'îœ'
Arch = 'ïŒƒ'
CentOS = 'ïŒ„'
Debian = 'ïŒ†'
EndeavourOS = 'ïŒ¢'
Fedora = 'ïŒŠ'
FreeBSD = 'ïŒŒ'
Garuda = 'ï…¼'
Gentoo = 'ïŒ'
Linux = 'ï…¼'
Macos = 'ïŒ‚'
Manjaro = 'ïŒ’'
Mariner = 'ï…¼'
Mint = 'ïŒ'
NetBSD = 'ï…¼'
NixOS = 'ïŒ“'
OpenBSD = 'ïŒ¨'
OpenCloudOS = 'î®ª'
openEuler = 'ï…¼'
openSUSE = 'ïŒ”'
OracleLinux = 'âŠ‚âŠƒ'
Pop = 'ïŒª'
Raspbian = 'ïŒ•'
Redhat = 'ïŒ–'
RedHatEnterprise = 'ïŒ–'
Solus = 'ïŒ­'
SUSE = 'ïŒ”'
Ubuntu = 'ïŒ›'
Unknown = 'ï„ˆ'
Windows = 'îœ'

[directory]
format = '[â”€](fg:current_line)[î‚¶](fg:pink)[ó°· ](fg:primary bg:pink)[î‚´](fg:pink bg:box)[$read_only]($read_only_style bg:box)[ $truncation_symbol$path](fg:foreground bg:box)[î‚´](fg:box)'
home_symbol = "~"
truncation_symbol = 'â€¦/'
truncation_length = 4
read_only = ' ó°®'
read_only_style = 'bold red'

[sudo]
format = '[$symbol](fg:primary bg:yellow)'
symbol = 'ó±„» '
disabled = false

[git_branch]
format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:primary bg:green)[î‚´](fg:green bg:box)[ $branch](fg:foreground bg:box)'
symbol = 'ï— '

[git_status]
format = '[( $all_status )](fg:foreground bg:box)'

[git_metrics]
added_style = 'bold green'
deleted_style = 'bold red'
format = '[([+$added]($added_style bg:box) )([-$deleted]($deleted_style bg:box) )](fg:foreground bg:box)[î‚´](fg:box)'
disabled = false

[nodejs]
format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:primary bg:green)[î‚´](fg:green bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
detect_files = ["package.json", ".node-version", "!bunfig.toml", "!bun.lockb"]

[bun]
format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:primary bg:green)[î‚´](fg:green bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = 'ğŸ¥Ÿ'

[deno]
format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:primary bg:green)[î‚´](fg:green bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'
symbol = 'ğŸ¦•'

[nix_shell]
symbol = "ïŒ“ "
format = '[â”€](fg:current_line)[î‚¶](fg:pink)[$symbol](fg:primary bg:pink)[î‚´](fg:pink bg:box)[ $state (\($name\))](fg:foreground bg:box)[î‚´](fg:box)'

[c]
symbol = "î˜ "
format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:primary bg:green)[î‚´](fg:green bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'

[rust]
symbol = "î¨"
format = '[â”€](fg:current_line)[î‚¶](fg:red)[$symbol](fg:primary bg:red)[î‚´](fg:red bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'

[golang]
symbol = "ó°Ÿ“ "
format = '[â”€](fg:current_line)[î‚¶](fg:green)[$symbol](fg:primary bg:green)[î‚´](fg:green bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'

[php]
symbol = "î˜ˆ"
format = '[â”€](fg:current_line)[î‚¶](fg:purple)[$symbol](fg:primary bg:purple)[î‚´](fg:purple bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'

[java]
symbol = "î‰– "
format = '[â”€](fg:current_line)[î‚¶](fg:orange)[$symbol](fg:primary bg:orange)[î‚´](fg:orange bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'

[dart]
symbol = "î™Œ "
format = '[â”€](fg:current_line)[î‚¶](fg:blue)[$symbol](fg:primary bg:blue)[î‚´](fg:blue bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'

[kotlin]
symbol = "î˜´"
format = '[â”€](fg:current_line)[î‚¶](fg:purple)[$symbol](fg:primary bg:purple)[î‚´](fg:purple bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'

[haskell]
symbol = "î˜Ÿ"
format = '[â”€](fg:current_line)[î‚¶](fg:pink)[$symbol](fg:primary bg:pink)[î‚´](fg:pink bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'

[python]
symbol = "î˜†"
format = '[â”€](fg:current_line)[î‚¶](fg:yellow)[$symbol](fg:primary bg:yellow)[î‚´](fg:yellow bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'

[docker_context]
symbol = "ïŒˆ"
format = '[â”€](fg:current_line)[î‚¶](fg:blue)[$context](fg:primary bg:blue)[î‚´](fg:blue bg:box)[ $version](fg:foreground bg:box)[î‚´](fg:box)'

[aws]
format = '[â”€](fg:current_line)[î‚¶](fg:purple)[$symbol](fg:primary bg:purple)[î‚´](fg:purple bg:box)[ $profile](fg:foreground bg:box)[î‚´](fg:box)'
symbol = 'â˜ï¸'

[fill]
symbol = 'â”€'
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[â”€](fg:current_line)[î‚¶](fg:orange)[ïƒ§ ](fg:primary bg:orange)[î‚´](fg:orange bg:box)[ $duration ](fg:foreground bg:box)[î‚´](fg:box)'

[shell]
format = '[â”€](fg:current_line)[î‚¶](fg:blue)[ï’‰ ](fg:primary bg:blue)[î‚´](fg:blue bg:box)[ $indicator](fg:foreground bg:box)[î‚´](fg:box)'
disabled = false

[time]
format = '[â”€](fg:current_line)[î‚¶](fg:purple)[ó°¦– ](fg:primary bg:purple)[î‚´](fg:purple bg:box)[ $time](fg:foreground bg:box)[î‚´](fg:box)'
time_format = '%H:%M:%S'
disabled = false

[username]
format = '[î‚´](fg:yellow bg:box)[ $user](fg:foreground bg:box)[î‚´](fg:box)'
show_always = true

[character]
format = """
[â•°â”€$symbol](fg:current_line) """
success_symbol = '[îŠ…îŠ…](fg:bold green)'
error_symbol = '[îŠ…îŠ…](fg:bold red)'
